name: Deploy Monsters React App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git Identity
        run: |
          git config --global user.name "Ilona Zaika"
          git config --global user.email "zaika.ilona.v@gmail.com"
    
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          # Install gh-pages package if not installed yet
          npm install gh-pages
          # Deploy to GitHub Pages using the token
          npx gh-pages -d build -r https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
